db.createCollection('LE07PARTIDO');
db.LE07PARTIDO.insert({
SIGLA:'UNIAO',
NOME:'COLIGACAO SAO PAULO PARA FRENTE'
});

db.LE07PARTIDO.insert({
SIGLA:'DEM',
NOME:'DEMOCRATAS'
});

db.LE07PARTIDO.insert({
SIGLA:'PCB',
NOME:'PARTIDO COMUNISTA BRASILEIRO'
});

db.LE07PARTIDO.insert({
SIGLA:'PCdoB',
NOME:'PARTIDO COMUNISTA DO BRASIL'
});

db.LE07PARTIDO.insert({
SIGLA:'PCO',
NOME:'PARTIDO DA CAUSA OPERÁRIA'
});

db.LE07PARTIDO.insert({
SIGLA:'PMN',
NOME:'PARTIDO DA MOBILIZAÇÃO NACIONAL'
});

db.LE07PARTIDO.insert({
SIGLA:'PMB',
NOME:'PARTIDO DA MULHER BRASILEIRA'
});

db.LE07PARTIDO.insert({
SIGLA:'PR',
NOME:'PARTIDO DA REPÚBLICA'
});

db.LE07PARTIDO.insert({
SIGLA:'PSDB',
NOME:'PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA'
});

db.LE07PARTIDO.insert({
SIGLA:'PDT',
NOME:'PARTIDO DEMOCRÁTICO TRABALHISTA'
});

db.LE07PARTIDO.insert({
SIGLA:'PM',
NOME:'PARTIDO DO MATHEUS'
});

db.LE07PARTIDO.insert({
SIGLA:'PM2',
NOME:'PARTIDO DO MATHEUS2'
});

db.LE07PARTIDO.insert({
SIGLA:'PM3',
NOME:'PARTIDO DO MATHEUS3'
});

db.LE07PARTIDO.insert({
SIGLA:'PMDB',
NOME:'PARTIDO DO MOVIMENTO DEMOCRÁTICO BRASILEIRO'
});

db.LE07PARTIDO.insert({
SIGLA:'PT',
NOME:'PARTIDO DOS TRABALHADORES'
});

db.LE07PARTIDO.insert({
SIGLA:'PEN',
NOME:'PARTIDO ECOLÓGICO NACIONAL'
});

db.LE07PARTIDO.insert({
SIGLA:'PHS',
NOME:'PARTIDO HUMANISTA DA SOLIDARIEDADE'
});

db.LE07PARTIDO.insert({
SIGLA:'NOVO',
NOME:'PARTIDO NOVO'
});

db.LE07PARTIDO.insert({
SIGLA:'PPS',
NOME:'PARTIDO POPULAR SOCIALISTA'
});

db.LE07PARTIDO.insert({
SIGLA:'PP',
NOME:'PARTIDO PROGRESSISTA'
});

db.LE07PARTIDO.insert({
SIGLA:'PPL',
NOME:'PARTIDO PÁTRIA LIVRE'
});

db.LE07PARTIDO.insert({
SIGLA:'PRTB',
NOME:'PARTIDO RENOVADOR TRABALHISTA BRASILEIRO'
});

db.LE07PARTIDO.insert({
SIGLA:'PRB',
NOME:'PARTIDO REPUBLICANO BRASILEIRO'
});

db.LE07PARTIDO.insert({
SIGLA:'PROS',
NOME:'PARTIDO REPUBLICANO DA ORDEM SOCIAL'
});

db.LE07PARTIDO.insert({
SIGLA:'PRP',
NOME:'PARTIDO REPUBLICANO PROGRESSISTA'
});

db.LE07PARTIDO.insert({
SIGLA:'PSC',
NOME:'PARTIDO SOCIAL CRISTÃO'
});

db.LE07PARTIDO.insert({
SIGLA:'PSDC',
NOME:'PARTIDO SOCIAL DEMOCRATA CRISTÃO'
});

db.LE07PARTIDO.insert({
SIGLA:'PSD',
NOME:'PARTIDO SOCIAL DEMOCRÁTICO'
});

db.LE07PARTIDO.insert({
SIGLA:'PSL',
NOME:'PARTIDO SOCIAL LIBERAL'
});

db.LE07PARTIDO.insert({
SIGLA:'PSOL',
NOME:'PARTIDO SOCIALISMO E LIBERDADE'
});

db.LE07PARTIDO.insert({
SIGLA:'PSB',
NOME:'PARTIDO SOCIALISTA BRASILEIRO'
});

db.LE07PARTIDO.insert({
SIGLA:'PSTU',
NOME:'PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO'
});

db.LE07PARTIDO.insert({
SIGLA:'PTB',
NOME:'PARTIDO TRABALHISTA BRASILEIRO'
});

db.LE07PARTIDO.insert({
SIGLA:'PTC',
NOME:'PARTIDO TRABALHISTA CRISTÃO'
});

db.LE07PARTIDO.insert({
SIGLA:'PTdoB',
NOME:'PARTIDO TRABALHISTA DO BRASIL'
});

db.LE07PARTIDO.insert({
SIGLA:'PTN',
NOME:'PARTIDO TRABALHISTA NACIONAL'
});

db.LE07PARTIDO.insert({
SIGLA:'PV',
NOME:'PARTIDO VERDE'
});

db.LE07PARTIDO.insert({
SIGLA:'REDE',
NOME:'REDE SUSTENTABILIDADE'
});

db.LE07PARTIDO.insert({
SIGLA:'SD',
NOME:'SOLIDARIEDADE'
});

db.LE07PARTIDO.insert({
SIGLA:'US',
NOME:'Ursal'
});

db.LE07PARTIDO.ensureIndex({SIGLA:1});
